

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Выше 3 Мета-теги ** должны прийти в первую очередь в голове; любой другой руководитель контент *после* эти теги -->  
    <title>404</title>
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <!-- Bootstrap -->  
    <link href="/../css/bootstrap.min.css" rel="stylesheet">
	<link href="/../css/starter-template.css" rel="stylesheet">
	<link href="/../css/theme.css" rel="stylesheet">
	  
  </head>
  <body>	  
	  
        <a href="/login">
            <button id="exit">
                Выход
            </button>
        </a>
		  
	<div class="container">
		<div class="starter-template">
			<h1>404</h1>
			<p class="lead">Запрашиваемая страница не найдена.</p>
		</div>
    </div>	  
	  
  </body>
</html>