
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Регистрация</title>

    <!-- Bootstrap core CSS -->
    <link href="/../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/../css/signin.css" rel="stylesheet">
	  <link href="/../css/theme.css" rel="stylesheet">
    
  </head>

  <body>

    <div class="container">
    
		<? if (isset($error)): ?>
			<div class="alert alert-danger" role="alert" align="center" ><? echo  $error; ?></div>
		<? endif; ?>
    
    <form class="form-signin" action="/register" method="post">
			<h2 class="form-signin-heading">Регистрация</h2>
			<label for="inputLogin" class="sr-only">Логин</label>
			<input type="login" id="inputLogin" class="form-control" placeholder="Логин" name="login" required autofocus>
			<label for="inputPassword" class="sr-only">Пароль</label>
			<input type="password" id="inputPassword" class="form-control" placeholder="Пароль" name="password" required>
			<label for="inputPassword" class="sr-only">Повторите пароль</label>
			<input type="password" id="inputPassword" class="form-control" placeholder="Пароль" name="password_repeat" required>
			<button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
		</form>

    </div> <!-- /container -->
    <div class="container">
        <div id="login" class="form-signin">
            <a href="/login">Авторизация</a>
        </div>
    </div>
  </body>
</html>
